# Generated by Django 5.2 on 2025-11-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_newscategory_news_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название организации')),
                ('price', models.FloatField()),
                ('grafik_raboty', models.TextField(verbose_name='График работы')),
                ('description', models.TextField(verbose_name='Описание')),
                ('phone_number', models.CharField(verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название вакансии')),
                ('price', models.IntegerField()),
                ('grafik_raboty', models.TextField(verbose_name='График работы')),
                ('description', models.TextField(verbose_name='Описание')),
                ('phone_number', models.CharField(verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансия',
                'ordering': ['title'],
            },
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-published_date'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.RenameField(
            model_name='mappoint',
            old_name='latitude',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='mappoint',
            old_name='longitude',
            new_name='lng',
        ),
        migrations.RenameField(
            model_name='mappoint',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='created_at',
            new_name='published_date',
        ),
        migrations.RemoveField(
            model_name='news',
            name='is_important',
        ),
        migrations.AddField(
            model_name='mappoint',
            name='type',
            field=models.CharField(default=None, verbose_name='тип'),
        ),
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news_images/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='news',
            name='short_description',
            field=models.CharField(default=None, verbose_name='Текст новости'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='top',
            field=models.BooleanField(default=False, verbose_name='топовые новости'),
        ),
    ]
